# setup-rin-windows.ps1 -- deploy Rin environment to Windows local Claude Code
#
# Steps:
#   1. Extract sync block from agent-config CLAUDE.md
#   2. Inline memory files into ~/.claude/CLAUDE.md (global)
#   3. Copy agents/ to ~/.claude/agents/
#   4. Copy memory/ to ~/.claude/projects/<encoded-cwd>/memory/ (multiple cwds)
#
# Called by bootstrap-rin.ps1, can also be run manually.

[CmdletBinding()]
param(
    [string]$AgentConfigDir = "$env:USERPROFILE\.cache\agent-config",
    [string]$ClaudeDir = "$env:USERPROFILE\.claude"
)

$ErrorActionPreference = "Stop"

$projectsMeta   = Join-Path $AgentConfigDir "projects-meta"
$memoryDir      = Join-Path $AgentConfigDir "projects\-root-projects\memory"
$sourceClaudeMd = Join-Path $projectsMeta "CLAUDE.md"
$sourceAgents   = Join-Path $projectsMeta "agents"

foreach ($p in @($sourceClaudeMd, $sourceAgents, $memoryDir)) {
    if (-not (Test-Path $p)) {
        Write-Error "source not found: $p"
        exit 1
    }
}

# Extract CLAUDE.md sync block (excluding SKIP ranges)
$beginMark = '<!-- BEGIN: claude-config-sync'
$endMark   = '<!-- END: claude-config-sync -->'
$skipBegin = '<!-- BEGIN-SKIP: claude-config-sync -->'
$skipEnd   = '<!-- END-SKIP: claude-config-sync -->'

$lines = Get-Content $sourceClaudeMd -Encoding UTF8
$inBlock = $false
$skipping = $false
$section = [System.Collections.Generic.List[string]]::new()

foreach ($line in $lines) {
    if ($line -like "*$beginMark*") { $inBlock = $true; $section.Add($line); continue }
    if ($line -like "*$endMark*")   { $section.Add($line); $inBlock = $false; continue }
    if ($line -like "*$skipBegin*") { $skipping = $true; continue }
    if ($line -like "*$skipEnd*")   { $skipping = $false; continue }
    if ($inBlock -and -not $skipping) { $section.Add($line) }
}

if ($section.Count -eq 0) {
    Write-Error "CLAUDE.md sync block not found in $sourceClaudeMd"
    exit 1
}

$sectionStr = ($section -join "`n")

# Build memory block (inline)
$memoryBlock = [System.Collections.Generic.List[string]]::new()
$memoryBlock.Add('<!-- BEGIN: claude-config-memory (auto-synced - do not edit) -->')
$memoryBlock.Add('## Memory')
$memoryBlock.Add('')
$memoryBlock.Add('Synced from agent-config projects/-root-projects/memory/.')
$memoryBlock.Add('')

$memIndex = Join-Path $memoryDir "MEMORY.md"
if (Test-Path $memIndex) {
    $memoryBlock.Add('### MEMORY.md (index)')
    $memoryBlock.Add('')
    $memoryBlock.Add((Get-Content $memIndex -Raw -Encoding UTF8).TrimEnd())
    $memoryBlock.Add('')
}

Get-ChildItem -Path $memoryDir -Filter "*.md" |
    Where-Object { $_.Name -ne "MEMORY.md" } |
    Sort-Object Name |
    ForEach-Object {
        $memoryBlock.Add("### $($_.Name)")
        $memoryBlock.Add('')
        $memoryBlock.Add((Get-Content $_.FullName -Raw -Encoding UTF8).TrimEnd())
        $memoryBlock.Add('')
    }

$memoryBlock.Add('<!-- END: claude-config-memory -->')
$memoryBlockStr = ($memoryBlock -join "`n")

# Write global CLAUDE.md
if (-not (Test-Path $ClaudeDir)) { New-Item -ItemType Directory -Path $ClaudeDir -Force | Out-Null }
$globalClaudeMd = Join-Path $ClaudeDir "CLAUDE.md"

$header = "# CLAUDE.md (Windows global - auto-generated by setup-rin-windows.ps1)`n`n"
$header += "This file is auto-synced from agent-config. Do not edit manually.`n"
$header += "master: https://github.com/keitaurano-del/agent-config`n`n"

$out = $header + $sectionStr + "`n`n" + $memoryBlockStr + "`n"

# Write with UTF-8 BOM so PowerShell 5.x reads it correctly
$utf8Bom = New-Object System.Text.UTF8Encoding $true
[System.IO.File]::WriteAllText($globalClaudeMd, $out, $utf8Bom)
Write-Host "OK global CLAUDE.md -> $globalClaudeMd"

# Copy agents
$agentsTarget = Join-Path $ClaudeDir "agents"
if (-not (Test-Path $agentsTarget)) { New-Item -ItemType Directory -Path $agentsTarget -Force | Out-Null }
Copy-Item -Path (Join-Path $sourceAgents "*.md") -Destination $agentsTarget -Force
Write-Host "OK agents -> $agentsTarget"

# Copy memory to auto-memory cwd buckets
$encodedCwds = @(
    "C--Users-keita",
    "C--Users-keita-projects",
    "C--Users-keita-logic",
    "C--Users-keita-assistant"
)

foreach ($enc in $encodedCwds) {
    $memTarget = Join-Path $ClaudeDir "projects\$enc\memory"
    if (-not (Test-Path $memTarget)) { New-Item -ItemType Directory -Path $memTarget -Force | Out-Null }
    Copy-Item -Path (Join-Path $memoryDir "*.md") -Destination $memTarget -Force
}
Write-Host "OK memory -> $($encodedCwds.Count) cwd buckets under $ClaudeDir\projects\"

Write-Host ""
Write-Host "Windows Rin setup complete."
