# setup-rin-windows.ps1 — Windows local Claude Code に凜環境を展開
#
# 動作:
#   1. agent-config の projects-meta/CLAUDE.md から sync ブロックを抽出
#   2. memory ファイルを inline 化して global CLAUDE.md (~\.claude\CLAUDE.md) に書き込み
#   3. agents/ を ~\.claude\agents\ にコピー
#   4. memory/ を ~\.claude\projects\<encoded-cwd>\memory\ にコピー（複数 cwd 対応）
#
# bootstrap-rin.ps1 から呼ばれる想定。手動実行も可。

[CmdletBinding()]
param(
    [string]$AgentConfigDir = "$env:USERPROFILE\.cache\agent-config",
    [string]$ClaudeDir = "$env:USERPROFILE\.claude"
)

$ErrorActionPreference = "Stop"

$projectsMeta = Join-Path $AgentConfigDir "projects-meta"
$memoryDir    = Join-Path $AgentConfigDir "projects\-root-projects\memory"
$sourceClaudeMd = Join-Path $projectsMeta "CLAUDE.md"
$sourceAgents   = Join-Path $projectsMeta "agents"

foreach ($p in @($sourceClaudeMd, $sourceAgents, $memoryDir)) {
    if (-not (Test-Path $p)) {
        Write-Error "source not found: $p"
        exit 1
    }
}

# ───────────────────────────────────────────────
# 1. CLAUDE.md sync ブロックを抽出（SKIP 範囲を除外）
# ───────────────────────────────────────────────
$beginMark = '<!-- BEGIN: claude-config-sync'
$endMark   = '<!-- END: claude-config-sync -->'
$skipBegin = '<!-- BEGIN-SKIP: claude-config-sync -->'
$skipEnd   = '<!-- END-SKIP: claude-config-sync -->'

$lines = Get-Content $sourceClaudeMd -Encoding UTF8
$inBlock = $false
$skipping = $false
$section = [System.Collections.Generic.List[string]]::new()

foreach ($line in $lines) {
    if ($line -like "*$beginMark*") { $inBlock = $true; $section.Add($line); continue }
    if ($line -like "*$endMark*")   { $section.Add($line); $inBlock = $false; continue }
    if ($line -like "*$skipBegin*") { $skipping = $true; continue }
    if ($line -like "*$skipEnd*")   { $skipping = $false; continue }
    if ($inBlock -and -not $skipping) { $section.Add($line) }
}

if ($section.Count -eq 0) {
    Write-Error "CLAUDE.md sync block not found in $sourceClaudeMd"
    exit 1
}

$sectionStr = ($section -join "`n")

# ───────────────────────────────────────────────
# 2. memory ブロックを inline 生成
# ───────────────────────────────────────────────
$memoryBlock = [System.Collections.Generic.List[string]]::new()
$memoryBlock.Add("<!-- BEGIN: claude-config-memory (auto-synced — do not edit) -->")
$memoryBlock.Add("## 蓄積メモリ")
$memoryBlock.Add("")
$memoryBlock.Add("agent-config の ``projects/-root-projects/memory/`` から sync。")
$memoryBlock.Add("")

$memIndex = Join-Path $memoryDir "MEMORY.md"
if (Test-Path $memIndex) {
    $memoryBlock.Add("### MEMORY.md (index)")
    $memoryBlock.Add("")
    $memoryBlock.Add((Get-Content $memIndex -Raw -Encoding UTF8).TrimEnd())
    $memoryBlock.Add("")
}

Get-ChildItem -Path $memoryDir -Filter "*.md" |
    Where-Object { $_.Name -ne "MEMORY.md" } |
    Sort-Object Name |
    ForEach-Object {
        $memoryBlock.Add("### $($_.Name)")
        $memoryBlock.Add("")
        $memoryBlock.Add((Get-Content $_.FullName -Raw -Encoding UTF8).TrimEnd())
        $memoryBlock.Add("")
    }

$memoryBlock.Add("<!-- END: claude-config-memory -->")
$memoryBlockStr = ($memoryBlock -join "`n")

# ───────────────────────────────────────────────
# 3. global CLAUDE.md (~\.claude\CLAUDE.md) に書き込み
# ───────────────────────────────────────────────
if (-not (Test-Path $ClaudeDir)) { New-Item -ItemType Directory -Path $ClaudeDir -Force | Out-Null }
$globalClaudeMd = Join-Path $ClaudeDir "CLAUDE.md"

$out = @"
# CLAUDE.md (Windows global — auto-generated by setup-rin-windows.ps1)

このファイルは agent-config から自動同期されます。手動編集しないでください。
master: https://github.com/keitaurano-del/agent-config

$sectionStr

$memoryBlockStr
"@

Set-Content -Path $globalClaudeMd -Value $out -Encoding UTF8 -NoNewline
Write-Host "OK global CLAUDE.md -> $globalClaudeMd"

# ───────────────────────────────────────────────
# 4. agents/ をコピー
# ───────────────────────────────────────────────
$agentsTarget = Join-Path $ClaudeDir "agents"
if (-not (Test-Path $agentsTarget)) { New-Item -ItemType Directory -Path $agentsTarget -Force | Out-Null }
Copy-Item -Path (Join-Path $sourceAgents "*.md") -Destination $agentsTarget -Force
Write-Host "OK agents -> $agentsTarget"

# ───────────────────────────────────────────────
# 5. memory/ を auto-memory 用パスにコピー（複数 cwd 対応）
#    Claude Code の auto-memory は ~/.claude/projects/<encoded-cwd>/memory/ を読む。
#    Windows の cwd は "C:\Users\keita\..." を "C--Users-keita-..." にエンコードする。
# ───────────────────────────────────────────────
$encodedCwds = @(
    "C--Users-keita",
    "C--Users-keita-projects",
    "C--Users-keita-logic",
    "C--Users-keita-assistant"
)

foreach ($enc in $encodedCwds) {
    $memTarget = Join-Path $ClaudeDir "projects\$enc\memory"
    if (-not (Test-Path $memTarget)) { New-Item -ItemType Directory -Path $memTarget -Force | Out-Null }
    Copy-Item -Path (Join-Path $memoryDir "*.md") -Destination $memTarget -Force
}
Write-Host "OK memory -> $($encodedCwds.Count) cwd buckets under $ClaudeDir\projects\"

Write-Host ""
Write-Host "Windows Rin setup complete."
